---
# tasks file for ocp-prepare-prereqs

- name: Check if /etc/named.conf already exists
  tags: conf_dns
  stat:
    path: /etc/named.conf
  register: named_exists  

- name: Create named.conf if not exists
  tags: conf_dns
  file:
    dest: /etc/named.conf
    owner: root
    group: root
    mode: '0755'    
    state: touch
  when: named_exists.stat.exists == False 

- blockinfile:
    dest: /etc/named.conf
    block: "{{ lookup('template', 'named.j2') }}"
  tags: conf_dns        

- name: Check if /var/lib/{{zone_name}}.zone already exists
  tags: conf_dns
  stat:
    path: /var/named/{{zone_name}}.zone
  register: named_exists  

- name: Create /var/lib/{{zone_name}}.zone if not exists
  tags: conf_dns
  file:
    dest: /var/named/{{zone_name}}.zone
    owner: root
    group: root
    mode: '0755'    
    state: touch
  when: named_exists.stat.exists == False 

- blockinfile:
    tags: conf_dns    
    dest: /var/named/{{zone_name}}.zone
    block: "{{ lookup('template', 'dns-zone.j2') }}"

- name: Check if /var/named/{{reverse_zone_name}}.zone already exists
  tags: conf_dns
  stat:
    path: /var/named/{{reverse_zone_name}}.zone
  register: named_exists  

- name: Create /var/named/{{reverse_zone_name}}.zone if not exists
  tags: conf_dns
  file:
    dest: /var/named/{{reverse_zone_name}}.zone
    owner: root
    group: root
    mode: '0755'    
    state: touch
  when: named_exists.stat.exists == False 

- blockinfile:
    tags: conf_dns    
    dest: /var/named/{{reverse_zone_name}}.zone
    block: "{{ lookup('template', 'dns-reverse-zone.j2') }}"

- name: Define reverse zone file
  tags: conf_dns
  template:
    src: dns-reverse-zone.j2
    dest: /var/named/{{reverse_zone_name}}.zone
    owner: root
    group: root
    mode: '0755'    

- name: Restart and enable dns-server
  systemd:
    state: restarted
    enabled: yes    
    daemon_reload: yes
    name: named-chroot 

- name: Define dhcp conf file
  tags: conf_dhcp
  template:
    src: dhcp.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0755'    

- name: Restart and enable dhcp
  systemd:
    state: restarted
    enabled: yes    
    daemon_reload: yes
    name: dhcpd  

- name: Set selinux for haproxy
  command: setsebool -P haproxy_connect_any on

- name: Set resolv for local dns
  command: "nmcli con mod {{ if_name }} ipv4.dns {{ dns_ip }}"

- name: Restart NM
  systemd:
    state: restarted   
    name: NetworkManager  

- name: Define haproxy conf file
  tags: conf_haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root    

- name: Restart and enable haproxy
  systemd:
    state: restarted
    enabled: yes    
    daemon_reload: yes
    name: haproxy  

- name: Configure firewalld services
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled      
  with_items:
    - dns
    - dhcp
    - http
    - https

- name: Configure firewalld ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled      
  with_items:
    - "6443/tcp"
    - "22623/tcp"
